export const truthGb = [
  "Qual foi seu primeiro pensamento sobre o outro hoje?",
  "Qual parte do seu corpo você mais gosta que o outro toque?",
  "Qual a memória mais engraçada que temos juntos?",
  "Se você pudesse repetir um momento nosso, qual seria?",
  "O que você gostaria que o outro fizesse mais vezes?",
  "Qual é a próxima fantasia que realizaremos?",
  "Qual é a coisa mais sexy que o teu parceiro faz?",
  "Qual é a coisa mais estúpida que já fizeste durante o sexo?",
  "Se pudesse escolher uma pessoa para um ménage com você e seu parceiro, quem seria?",
  "Qual parte do meu corpo você acha mais irresistível?",
  "Se você pudesse repetir um momento quente nosso, qual seria?",
  "O que eu faço sem perceber que te deixa com vontade de me beijar?",
  "Tem alguma roupa minha que te faz pensar besteira?",
  "O que você mais sente falta quando não estamos juntos?",
  "Você já ficou com ciúmes de algo que não me contou?",
  "Você já me desejou em um momento em que não podia demonstrar?",
  "Qual provocação você acha que eu deveria fazer mais vezes?",
  "Tem algo que gostaria que eu fizesse, mas ainda não teve coragem de pedir?",
]