export const truthSafe = [
  "Qual foi a sua maior vergonha?",
  "Você já contou uma mentira para um amigo próximo?",
  "Qual é o seu maior medo?",
  "Qual sua mania mais estranha?",
  "Qual a última vez que você fez algo pela primeira vez?",
  "Já sonhou com alguém dessa sala?",
  "Se você pudesse desconvidar alguém desta brincadeira, quem seria?",
  "Qual sua compra mais impulsiva e da qual se arrepende?",
  "Com quem desta sala você ficaria?",
  "Qual seu crush famoso?",
  "Qual sua última promessa não cumprida?",
  "Já pesquisou seu nome completo no Google? O que encontrou?",
  "Com quem você gostaria de passar seu último dia de vida?",
  "Qual o último livro que você leu?",
  "Já contou o segredo de alguém?",
  "Com quantos anos deu seu primeiro beijo?",
  "Qual a história mais engraçada que já aconteceu com você?",
  "Já foi penetra em uma festa?",
  "O que te faz único?",
  "O que fez que seus pais não podem saber?",
  "Já mentiu estar doente pra faltar ao trabalho?",
  "Já saiu mais cedo do restaurante pra não dividir a conta?",
  "Do que mais se orgulha em você?",
  "Já fez xixi na piscina?",
  "O que você faria se ganhasse na loteria?",
  "Qual seu sonho mais bizarro?",
  "Já deixou de seguir alguém nas redes sociais e disse que foi 'bug do sistema'?",
  "Já teve conta falsa pra stalkear namorada(o)?",
  "Qual seu recorde sem utilizar celular/internet?",
  "Qual a situação mais constrangedora em que soltou um pum?",
  "Já repassou presente que ganhou e não gostou?",
  "Qual a maior loucura de amor que você já fez?",
  "Já mentiu a idade pra entrar em uma festa?",
  "Qual seu medo mais bobo?",
  "Qual seu apelido mais constrangedor?",
  "Se você pudesse escolher um superpoder, qual seria?",
  "Já namorou alguém gostando de outra pessoa?",
  "Qual a maior quantidade de dias já passou sem tomar banho?",
  "Qual seu maior arrependimento?",
  "Se você pudesse voltar no tempo, qual momento escolheria?",
  "Já mentiu nesse jogo?",
  "Casaria com alguém que não ama por 1 milhão de reais?",
  "Já viveu um amor proibido?",
  "Já fingiu que sabia sobre um assunto pra não parecer desinformado?",
  "Qual a maior vergonha que você passou em público?",
  "O que faria se fosse invisível?",
  "Já esteve apaixonado(a) por um(a) amigo(a) em segredo?",
  "Já foi traído(a)?",
  "Qual a maior mentira que você já contou?",
  "Já curtiu post sem querer enquanto stalkeava alguém?",
  "Como deixou de acreditar no Papai Noel?",
  "Qual o pior presente que você já ganhou?",
  "Você precisa se casar com um dos jogadores, quem escolheria?",
  "Qual a coisa mais estranha que você já fez por dinheiro?",
  "Qual sua maior decepção amorosa?",
  "Já fez seu mapa astral?",
  "Qual superstição você considera mais esquisita?",
  "Em sua opinião, quem nesta sala é menos honesto?",
  "Música ou filme?",
  "Já deu spoiler de propósito e fingiu ser sem querer?",
  "Diga um filme ou série que você assistiu, ou está assistindo, mas tem vergonha de admitir?",
  "Já se apaixonou por um professor?",
  "Qual a situação mais perigosa pela qual você passou?",
  "1 bilhão de reais ou a paz mundial?",
  "Já mandou mensagem para a pessoa errada?",
  "Qual seu sonho mais estranho?",
  "Já falou mal de alguém e depois virou amigo(a) da pessoa?",
  "Qual o melhor destino para passar férias?",
  "Qual seu maior desastre culinário?",
  "Já usou a mesma roupa por três dias seguidos?",
  "Qual a situação mais constrangedora você já fez seus pais passarem?",
  "Qual a profissão dos seus sonhos?",
  "Quem é/foi o grande amor da sua vida?",
  "Se pudesse renascer como um animal, qual escolheria?",
  "O que mais te irrita nas pessoas?",
  "Qual seu princípio moral inegociável?",
  "Quem você escolheria neste grupo para ser seu mentor espiritual?",
  "Qual o conselho mais 'errado' que você já deu?",
  "Já encobriu a traição de um(a) amigo(a)?",
  "Qual seu talento oculto?",
  "Qual filme marcou sua infância?",
  "Já fez algo errado e culpou outra pessoa?",
  "Qual o maior defeito do seu melhor amigo?",
  "Nunca mais tomar banho ou acordar de madrugada todos os dias?",
  "Já riu de piada que não entendeu pra não ficar de fora?",
  "Se você tivesse um podcast, do que falaria nele?",
  "Milionário por um dia! Como você gastaria 1 milhão em apenas uma noite?",
  "Já usou algum aplicativo de relacionamento?",
  "Já fez algo proibido e não foi descoberto?",
  "Se pudesse escolher alguém do grupo para trocar de corpo, quem seria?",
  "Qual a pior nota que já teve na escola/faculdade?",
  "Já fingiu estar dormindo para não dar lugar no ônibus?",
  "Se tivesse de comer a mesma coisa por um ano, o que seria?",
  "Qual seu pior primeiro encontro?",
  "Qual a coisa mais nojenta que você já fez?",
  "Já se arrependeu de falar a verdade?",
  "Se pudesse aconselhar alguém do passado, quem seria?",
  "Qual seu maior pecado?",
  "Deste grupo, a quem você confiaria seu diário?",
  "Quais seriam suas últimas palavras?",
  "Já passou por um conhecido e fingiu que não viu pra não ter que conversar?",
  "O que a maioria das pessoas pensa que é verdade sobre você, mas não é?",
  "Qual foi a razão mais ridícula pela qual terminou com alguém?",
  "O que você adora, mas tem vergonha de admitir?",
  "Qual foi a última coisa que pesquisou no seu telefone?",
  "Qual seria a primeira coisa que você faria se acordasse por um dia sendo do gênero oposto?",
  "Qual foi a pessoa mais aleatória que stalkeou nas redes sociais?",
  "Quando foi a última vez que chorou e por quê?",
  "Conte uma coisa que espera que seus pais nunca descubram.",
  "Quantos dias já passou sem tomar banho?",
  "Qual foi o pior presente que já deu para alguém?",
  "O que mais te faz sentir borboletas no estômago?",
  "O que mais te faz sentir frio na barriga?",
  "Qual foi a maior mentira que contou para faltar o trabalho?",
  "O que você faria se tivesse uma dor de barriga em um banheiro público, mas acabasse o papel higiênico?",
  "Qual é a mania mais nojenta que você tem?",
  "Qual foi a coisa mais embaraçosa que já fez?",
  "Já fez xixi nas calças depois de adulto?",
  "Quando foi a última vez que fez xixi na cama?",
  "Conte algo infantil que você ainda faz.",
  "Qual é a coisa mais estranha ou vergonhosa que já fez por dinheiro?",
  "Você já fez cocô nas calças em público?",
  "Se pudesse mudar de vida com uma celebridade por um dia, com quem seria?",
  "Qual é a maior mentira que já contou para alguém da sua família?",
  "Qual foi o momento mais inapropriado em que já soltou pum?",
  "Já se arrependeu imediatamente após enviar uma mensagem? Qual foi?",
  "Você já vomitou em público e teve que engolir?",
  "Por que você terminou com seu último namorado ou namorada?",
  "Qual a foto mais constrangedora que tem no seu telefone?",
  "Se acha bonito(a)?",
  "Dá uma olhada dentro do vaso sanitário antes de dar descarga?",
  "Quando foi a última vez que não conseguiu chegar a tempo ao banheiro?",
  "Qual o 'caminho' online mais longo que já fez para stalkear alguém?",
  "Que erro simples você ainda comete com frequência?",
  "Qual coisa que todo mundo sabe fazer, menos você?",
  "Qual a mania de limpeza que você tem e os outros acham frescura?",
  "Qual o talento estranho que você tem?",
  "Qual o passeio que você já fez que foi mais 'rolê errado' e você só queria fugir?",
  "Qual a mistura de comidas estranhas de que você gosta?",
  "Qual a maior vergonha que você já passou no meio da rua?",
  "Você já partiu o coração de alguém?",
  "Se você conhecesse um gênio, quais seriam seus três desejos?",
  "Qual foi a pior coisa que alguém fez com você?",
  "",
];
