export const dareSafe = [
  "Imite um animal por 10 segundos.",
  "Dance sem música por 15 segundos.",
  "Fale algo engraçado com sotaque diferente.",
  "Imite um bacon fritando.",
  "Tente lamber o cotovelo de olhos fechados.",
  "Faça uma foto com sua careta mais estranha e publique na sua rede social.",
  "Fale o alfabeto de trás pra frente.",
  "Dance lambada com a pessoa do seu lado.",
  "Mostre a última foto do seu celular (do álbum 'Apagados').",
  "Curta a última foto do seu ex nas redes sociais.",
  "Faça uma demonstração de kung fu.",
  "Tente fazer um arco-íris com a língua.",
  "Conte sua pior piada e gargalhe dela.",
  "Dê uma volta na sala andando feito caranguejo.",
  "Crie uma coreografia de dança contemporânea e arrase na pista!",
  "Dê o telefone na mão da pessoa à sua frente e deixe ela publicar alguma coisa nas suas redes sociais.",
  "Você é um jogador de futebol que acaba de fazer um gol. Comemore!",
  "Fama por um dia! Imite uma celebridade.",
  "Massageie os pés da pessoa ao lado.",
  "Fale com sua voz mais engraçada pelos próximos 3 minutos.",
  "Dê a previsão do tempo com voz de narrador de futebol.",
  "Dance sua melhor coreografia.",
  "Cante o refrão de uma música com a língua pra fora.",
  "Faça uma automaquiagem imitando uma blogueira.",
  "Dance em silêncio até adivinharem qual é a música.",
  "Descreva o sabor da água como um especialista faria.",
  "Publique sua última selfie.",
  "Responda à última mensagem recebida com: 'Os aliens estão voltando!!!'",
  "Faça um discurso de agradecimento como se tivesse ganhado um Oscar.",
  "Conte uma notícia trágica enquanto gargalha.",
  "Beba água de um potinho, como um cachorro.",
  "Fale uma frase inteira com todas as palavras começando com a letra 'P'.",
  "Gargareje uma canção de ninar.",
  "Troque de meias com a pessoa ao lado.",
  "Reconte o filme 'O Rei Leão' em apenas uma frase.",
  "Viva la vida loca!!! Dance por 1 minuto como se não houvesse amanhã!",
  "Passe o resto do jogo sem usar o celular.",
  "Finja estar em um show tocando uma guitarra imaginária.",
  "Fale cantando por uma rodada.",
  "Escolha alguém do grupo para ficar de mãos dadas até o final do jogo.",
  "Leia a mão da pessoa à sua frente e veja seu futuro!",
  "Desenhe um autorretrato de olhos fechados.",
  "Invente uma canção e ensine pra galera. Cantem em coro!",
  "Cante 'Parabéns pra você' fingindo soluço.",
  "Ligue pra sua última chamada recebida e diga que está com saudade.",
  "Tente fazer malabarismos com três objetos que o grupo escolher.",
  "Tente beber um copo de água usando os seus pés.",
  "Molhe o rosto e passe ele em um prato com farinha.",
  "Ligue para uma lanchonete ou pizzaria e tente desabafar com o atendente, dizendo que seu namorado ou namorada terminou contigo.",
  "Ligue para sua mãe dizendo que quer sua chupeta.",
  "Ligue para o quinto contato da lista do seu telefone e cante um trecho de uma música que o grupo escolher.",
  "Crie um rap sobre sua situação amorosa atual.",
  "Finja ser o animal de estimação da pessoa à sua esquerda por 3 rodadas.",
  "Finja que você é um peixe se debatendo fora d’água.",
  "Finja que você está parindo uma criança.",
  "Fale com um sotaque diferente por 8 rodadas.",
  "Faça uma serenata para alguém do grupo.",
  "Faça uma mímica descrevendo seu filme favorito para que o grupo adivinhe.",
  "Faça o quadradinho de oito (ou tente!).",
  "Dance alguma música que o grupo escolher.",
  "Cante uma música de funk como se fosse uma ópera.",
  "Se enrole em papel higiênico até ficar parecido com uma múmia.",
  "Ligue para um restaurante e tente manter o atendente em linha por cinco minutos, imitando um estrangeiro falando português.",
  "Dance forró com uma vassoura.",
  "Imite uma minhoca no chão.",
  "Fale com voz de bebê até o final do jogo.",
  "Procure uma moeda com a boca em um prato cheio de farinha.",
  "Quem é a pessoa com quem você mais se arrepende de ter ficado?",
  
];