export const dareCaliente = [
  "Tente fazer malabarismos com três objetos que o grupo escolher.",
  "Tente beber um copo de água usando os seus pés.",
  "Molhe o rosto e passe ele em um prato com farinha.",
  "Ligue para uma lanchonete ou pizzaria e tente desabafar com o atendente, dizendo que seu namorado ou namorada terminou contigo.",
  "Ligue para sua mãe dizendo que quer sua chupeta.",
  "Ligue para o quinto contato da lista do seu telefone e cante um trecho de uma música que o grupo escolher.",
  "Crie um rap sobre sua situação amorosa atual.",
  "Finja ser o animal de estimação da pessoa à sua esquerda por 3 rodadas.",
  "Finja que você é um peixe se debatendo fora d’água.",
  "Finja que você está parindo uma criança.",
  "Fale com um sotaque diferente por 8 rodadas.",
  "Faça uma serenata para alguém do grupo.",
  "Faça uma mímica descrevendo seu filme favorito para que o grupo adivinhe.",
  "Faça o quadradinho de oito (ou tente!).",
  "Dance alguma música que o grupo escolher.",
  "Cante uma música de funk como se fosse uma ópera.",
  "Se enrole em papel higiênico até ficar parecido com uma múmia.",
  "Ligue para um restaurante e tente manter o atendente em linha por cinco minutos, imitando um estrangeiro falando português.",
  "Dance forró com uma vassoura.",
  "Imite uma minhoca no chão.",
  "Fale com voz de bebê até o final do jogo.",
  "Procure uma moeda com a boca em um prato cheio de farinha.",
  "Mande uma mensagem ousada para algum contato do seu celular 'acidentalmente'.",
  "Ligue para um amigo e diga que está grávida ou que vai ser pai.",
  "Faça uma apresentação de dança do ventre.",
  "Cheire as axilas da pessoa à sua direita.",
  "Coloque um cubo de gelo dentro da sua blusa.",
  "Mostre como você flerta trocando olhares com alguém da roda.",
  "Passe hidratante em suas mãos de forma sensual.",
  "Cante o seu funk pesadão favorito.",
  "Fique por 5 rodadas em uma posição escolhida pelo grupo.",
  "Coloque um cubo de gelo em uma xícara ou copo pequeno e tente pegar com a língua.",
  "Curta os 5 posts mais antigos da primeira pessoa que aparecer em seu feed do Instagram.",
  "Abra o TikTok e faça a primeira dancinha que surgir no feed.",
  "Diga um defeito de cada um dos participantes do jogo.",
  "Faça uma massagem no pé de uma das pessoas da roda.",
  "Imite todos os gestos da pessoa ao seu lado por 5 minutos.",
  "Role a tela da lista de telefone do seu celular até alguém mandar parar. Você terá que decidir se ligará para a pessoa ou excluirá o número.",
  "Ligue para um amigo(a) que não está fazendo aniversário para dar os parabéns.",
  "Deixe uma pessoa da roda retocar a sua maquiagem (se estiver sem, permita que alguém o(a) maquie).",
  "Conte o enredo do seu filme ou série preferido com a língua para fora.",
  "Tire suas meias com a boca.",
  "Chupe o seu dedão do seu pé.",
  "Sussurre com a pessoa a esquerda a coisa mais safada que você faria com a da sua direita.",
  "Desafio-te a desenhar uma imagem do teu parceiro nu.",
  "Massageie o pescoço da segunda pessoa à sua direita usando a tua boca.",
  "Pesquise uma nova posição sexual que quer experimentar e mostre para todos.",
  "Te desafio a simular um boquete numa garrafa.",
  "",
]